/*
 * Code generated by github.com/wilhuang/goi18n. DO NOT EDIT.
 * version: 1.0.0
 * date: 2024-04-24
 */
package lang

const _NUM_LANG uint16 = 2 // 不包含key

const (
	I18N_ZH_CN = "zh_CN"
	I18N_EN_US = "en_US"
)

var _default_langsort = [_NUM_LANG]string{
	I18N_ZH_CN,
	I18N_EN_US,
}

const (
	_start Code = 1000 + iota
	ENTRIE      // entrie description
	_end
)
