/*
 * Code generated by github.com/wilhuang/goi18n. DO NOT EDIT.
 * version: 1.0.0
 * date: 2024-04-24
 */
package lang

const (
	I18N_ZH_CN = "zh_CN"
	I18N_EN_US = "en_US"
)
const (
	I18N_ZH_CN_ID = 0
	I18N_EN_US_ID = 1
	I18N_LEN      = 2 // 不包含key，同时也是KeyId
)

var _LANGS = [I18N_LEN]string{
	I18N_ZH_CN,
	I18N_EN_US,
}

const (
	_start Code = 1000 + iota
	ENTRIE      // entrie description
	_end
)
